Rails/Blank:
  Enabled: false

Rails/Date:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'features/**/*'
    - 'app/controllers/admin/community_memberships_controller.rb'
    - 'app/controllers/admin/community_transactions_controller.rb'
    - 'app/controllers/application_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/jobs/page_loaded_job.rb'
    - 'app/mailers/community_mailer.rb'

Rails/Delegate:
  Exclude:
    - 'app/models/listing.rb'
    - 'app/models/person.rb'

Rails/DynamicFindBy:
  Enabled: false
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'features/**/*'

Rails/FilePath:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'features/**/*'
    - 'lib/tasks/**/*'
    - 'app/controllers/landing_page_controller.rb'
    - 'app/models/person.rb'
    - 'app/models/listing_image.rb'
    - 'app/services/paypal_service/paypal_service_injector.rb'
    - 'lib/jsroutes_middleware.rb'
    - 'lib/services/paypal_service/api/fake_api_implementation.rb'

Rails/FindBy:
  Exclude:
    - 'app/models/community.rb'
    - 'app/models/custom_fields/option_field.rb'
    - 'app/models/person.rb'

Rails/HasAndBelongsToMany:
  Exclude:
    - 'app/models/person.rb'
    - 'app/models/listing_shape.rb'
    - 'app/models/listing.rb'
    - 'app/models/category.rb'

Rails/Output:
  Exclude:
    - 'app/view_utils/intercom_helper.rb'
    - 'app/jobs/transaction_automatically_confirmed_job.rb'
    - 'app/jobs/transaction_canceled_job.rb'
    - 'app/mailers/community_mailer.rb'
    - 'lib/selenium_webdriver_phantomjs_monkey_patch.rb'

Rails/OutputSafety:
  Exclude:
    - 'app/controllers/admin/communities_controller.rb'
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/infos_controller.rb'
    - 'app/controllers/landing_page_controller.rb'
    - 'app/controllers/listings_controller.rb'
    - 'app/controllers/paypal_accounts_controller.rb'
    - 'app/controllers/paypal_service/checkout_orders_controller.rb'
    - 'app/controllers/people_controller.rb'
    - 'app/controllers/sessions_controller.rb'
    - 'app/controllers/terms_controller.rb'
    - 'app/controllers/testimonials_controller.rb'
    - 'app/controllers/topbar_api_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/helpers/icon_helper.rb'
    - 'app/helpers/listings_helper.rb'
    - 'app/helpers/transaction_helper.rb'
    - 'app/services/custom_landing_page/markdown_helper.rb'
    - 'app/utils/uuid_utils.rb'

Rails/Present:
  Enabled: false

Rails/ReadWriteAttribute:
  Exclude:
    - 'app/models/listing.rb'
    - 'app/models/paypal_ipn_message.rb'
    - 'app/models/transaction.rb'
    - 'app/models/transaction_process.rb'

Rails/SkipsModelValidations:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'features/**/*'
    - 'app/controllers/admin/categories_controller.rb'
    - 'app/controllers/admin/community_memberships_controller.rb'
    - 'app/controllers/admin/listing_shapes_controller.rb'
    - 'app/controllers/i18n_controller.rb'
    - 'app/controllers/listings_controller.rb'
    - 'app/controllers/sessions_controller.rb'
    - 'app/controllers/terms_controller.rb'
    - 'app/jobs/download_listing_image_job.rb'
    - 'app/jobs/handle_paypal_ipn_message_job.rb'
    - 'app/jobs/page_loaded_job.rb'
    - 'app/mailers/community_mailer.rb'
    - 'app/mailers/person_mailer.rb'
    - 'app/models/community.rb'
    - 'app/models/custom_field.rb'
    - 'app/models/custom_field_option.rb'
    - 'app/models/invitation.rb'
    - 'app/models/listing.rb'
    - 'app/models/message.rb'
    - 'app/models/person.rb'
    - 'app/services/confirm_conversation.rb'
    - 'app/services/email_service/ses/synchronize.rb'
    - 'app/services/email_service/store/address.rb'
    - 'app/services/listing_service/api/listings.rb'
    - 'app/services/listing_service/store/listing.rb'
    - 'app/services/marketplace_service/conversation.rb'
    - 'app/services/marketplace_service/listing.rb'
    - 'app/services/marketplace_service/transaction.rb'
    - 'app/services/paypal_service/store/paypal_account.rb'
    - 'app/services/transaction_service/store/transaction.rb'
    - 'app/services/user_service/api/users.rb'
    - 'lib/active_sessions_helper.rb'

Rails/TimeZone:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'features/**/*'
    - 'lib/services/paypal_service/test_merchant.rb'
    - 'lib/active_sessions_helper.rb'
    - 'app/controllers/admin/community_memberships_controller.rb'
    - 'app/controllers/admin/community_transactions_controller.rb'
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/confirmations_controller.rb'
    - 'app/controllers/int_api/marketplaces_controller.rb'
    - 'app/controllers/invitations_controller.rb'
    - 'app/controllers/listings_controller.rb'
    - 'app/controllers/people_controller.rb'
    - 'app/controllers/sitemap_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/jobs/page_loaded_job.rb'
    - 'app/mailers/community_mailer.rb'
    - 'app/mailers/mail_preview.rb'
    - 'app/mailers/person_mailer.rb'
    - 'app/models/community.rb'
    - 'app/models/community_membership.rb'
    - 'app/models/conversation.rb'
    - 'app/models/email.rb'
    - 'app/models/invitation.rb'
    - 'app/models/listing.rb'
    - 'app/models/person.rb'
    - 'app/services/custom_landing_page/caching.rb'
    - 'app/services/custom_landing_page/landing_page_store_db.rb'
    - 'app/services/email_service/store/address.rb'
    - 'app/services/listing_service/store/listing.rb'
    - 'app/services/marketplace_service/transaction.rb'
    - 'app/services/plan_service/api/no_plans.rb'
    - 'app/services/plan_service/api/plans.rb'
    - 'app/services/s3_uploader.rb'
    - 'app/services/timing_service.rb'
    - 'app/services/user_service/api/auth_tokens.rb'
    - 'app/utils/maintenance.rb'
    - 'app/utils/service_client/middleware/timing.rb'
    - 'app/utils/time_utils.rb'

Rails/Validation:
  Exclude:
    - 'app/models/auth_token.rb'
    - 'app/models/billing_agreement.rb'
    - 'app/models/category_translation.rb'
    - 'app/models/comment.rb'
    - 'app/models/community.rb'
    - 'app/models/community_customization.rb'
    - 'app/models/community_membership.rb'
    - 'app/models/community_translation.rb'
    - 'app/models/custom_field.rb'
    - 'app/models/custom_field_option.rb'
    - 'app/models/custom_field_values/date_field_value.rb'
    - 'app/models/custom_field_values/dropdown_field_value.rb'
    - 'app/models/custom_field_values/numeric_field_value.rb'
    - 'app/models/custom_field_values/text_field_value.rb'
    - 'app/models/custom_fields/checkbox_field.rb'
    - 'app/models/custom_fields/dropdown_field.rb'
    - 'app/models/custom_fields/numeric_field.rb'
    - 'app/models/email.rb'
    - 'app/models/feature_flag.rb'
    - 'app/models/feedback.rb'
    - 'app/models/invitation.rb'
    - 'app/models/listing.rb'
    - 'app/models/marketplace_setup_steps.rb'
    - 'app/models/menu_link.rb'
    - 'app/models/menu_link_translation.rb'
    - 'app/models/message.rb'
    - 'app/models/order_permission.rb'
    - 'app/models/payment_settings.rb'
    - 'app/models/paypal_ipn_message.rb'
    - 'app/models/paypal_payment.rb'
    - 'app/models/paypal_process_token.rb'
    - 'app/models/paypal_refund.rb'
    - 'app/models/paypal_token.rb'
    - 'app/models/person.rb'
    - 'app/models/testimonial.rb'
    - 'app/models/transaction.rb'

Rails/UniqBeforePluck:
  Exclude:
    - 'app/services/marketplace_service/inbox.rb'

Rails/LexicallyScopedActionFilter:
  Exclude:
    - 'app/controllers/**/*'

Rails/ActiveRecordOverride:
  Exclude:
    - 'app/models/landing_page_version/section/base.rb'